### ISSUE TITLE
AudioNodes are not recovered correctly by the system GC

### ISSUE THREAD

**Issue by Yoitsu-Holo** [KristofferStrube/Blazor.WebAudio#2]
when I'm using this library, the **AudioSourceBufferNode** node (other nodes should have this problem as well) is not recovered correctly by the system GC (even if I call the StopAsync and DisposeAsync method manually)

Here is my code:

```csharp
// private AudioBufferSourceNode? _audioBuffer;

if (_audioBuffer is not null)
{
	await _audioBuffer.StopAsync();
	await _audioBuffer.DisconnectAsync();
	await _audioBuffer.DisposeAsync();
}
_audioBuffer = null;
```

I also found that in the library's Demo, for example in the **"AudioPlayer"** menu, when I keep pausing and playing my audio, none of the previously created audio nodes are destroyed correctly (you can even create thousands of nodes if you want to, until the memory runs out).

However, I don't have this problem when using native JavaScript code, here is my simple test code:

```JS
<!DOCTYPE html>
<html>

<body>
	<button id="controlButton">Play</button>

	<script>
		let context = new (window.AudioContext || window.webkitAudioContext)();
		let source = null;
		let audioBuffer = null;

		document.getElementById('controlButton').addEventListener('click', function () {
			if (this.textContent === 'Play') {
				startAudio();
				this.textContent = 'Pause';
			} else {
				stopAudio();
				this.textContent = 'Play';
			}
		});

		function startAudio() {
			source = context.createBufferSource();
			source.buffer = audioBuffer;
			source.loop = true;
			source.connect(context.destination);
			source.start(0);
		}

		function stopAudio() {
			source.stop(0);
		}

		window.fetch('bgm01.ogg').then(response =>
			response.arrayBuffer()
		).then(arrayBuffer =>
			context.decodeAudioData(arrayBuffer)
		).then(decodedAudioData => {
			audioBuffer = decodedAudioData;
		});
	</script>
</body>

</html>
```

Although some nodes may not be destroyed in time, they will eventually be recovered correctly at some GC.

My environment is:

- Microsoft.AspNetCore.Components.WebAssembly 8.0.4 
- latest version of the library, "0.1.0-alpha.5".

The browser used for testing was Chrome 125.0.6422.76 and the Audion plugin was used to view the audio nodes present on the page in the developer interface.

Looking forward to your reply.

**Comment by KristofferStrube** [comment]
Hey @Yoitsu-Holo, thanks for your interest in the project. :)

I will check out the AudioPlayer sample to see if I have missed releasing any references.

In your sample, how do you construct the `AudioBufferSourceNode`? This is important as the flag that decides whether the wrapper should release its reference once disposed is set differently depending on how the wrapper is constructed.

**Comment by KristofferStrube** [comment]
I also made a new alpha release with this fix.

**Comment by KristofferStrube** [comment]
Awesome!
