### ISSUE TITLE
Getting the raw data

### ISSUE THREAD

**Issue by shahabfar** [KristofferStrube/Blazor.WebAudio#3]
Hi,

Actually, this is a question.

Is it possible to access raw audio data from the microphone using your library, so that I can generate a waveform similar to the one in the attached image? If so, could you please guide me through the process?

Thanks

![bumblebee](https://github.com/KristofferStrube/Blazor.WebAudio/assets/36984027/cb9595f4-f5cd-439f-beec-2d6b114dc6cb)

**Comment by KristofferStrube** [comment]
Hey @shahabfar, thanks for your interest in the library.

I've added a sample that is somewhat close to what you have shown [here in the MediaStream demo](https://kristofferstrube.github.io/Blazor.WebAudio/AnalyzeMediaStream)

![image](https://github.com/KristofferStrube/Blazor.WebAudio/assets/11569642/dfec8779-1269-412a-9f6d-20a6f23efee4)

This kind of chart is called an audio amplitude chart. Your picture also represents that the different channels have different volumes at different times whereas mine simply handles mono-sound. It should be relatively easy to achieve this as well by using the AudioSplitterNode before parsing data to two individual analysers.

You can find the code for my Amplitude plot here: [AmplitudePlot.razor.cs](https://github.com/KristofferStrube/Blazor.WebAudio/blob/main/samples/KristofferStrube.Blazor.WebAudio.WasmExample/Shared/AmplitudePlot.razor.cs) and here [AmplitudePlot.razor](https://github.com/KristofferStrube/Blazor.WebAudio/blob/main/samples/KristofferStrube.Blazor.WebAudio.WasmExample/Shared/AmplitudePlot.razor)

**Comment by shahabfar** [comment]
Thank you so much.

**Comment by shahabfar** [comment]
Hello 
I need something completely like this, but in Blazor:
https://wavesurfer.xyz/examples/?record.js

**Comment by KristofferStrube** [comment]
Sounds like a great project. :D
