### ISSUE TITLE
Please provide an example of the recording captured via microphone

### ISSUE THREAD

**Issue by risogolo** [KristofferStrube/Blazor.WebAudio#4]
Can you please provide an example, that will show how to capture the audio to some variable (ideally byte[] or similar) via microphone so I can then play that recording on a page or send the byte[] to some backend endpoint , I cannot figure it out.

**Comment by KristofferStrube** [comment]
Hey @risogolo, after some investigation, I found that this is not possible with the `Web Audio API`.

If you want to record a `MediaStream` or a `MediaStreamTrack` I recommend that you take a look at the [MediaStream Recording API](https://www.w3.org/TR/mediastream-recording/). I don't have a wrapper for that API, but the types introduced in [Blazor.MediaCaptureStreams](https://github.com/KristofferStrube/Blazor.MediaCaptureStreams) should integrate well with any JSInterop you would make yourself.

Check out the related issue on implementing a wrapper for the *MediaStream Recording API* here: https://github.com/KristofferStrube/Blazor.MediaCaptureStreams/issues/4
