### ISSUE TITLE
How to save the audio ? 

### ISSUE THREAD

**Issue by b4naki** [KristofferStrube/Blazor.WebAudio#6]
First of all thank you very much for all the effort you put in here. 

I am following the samples on recording audio 
https://github.com/KristofferStrube/Blazor.WebAudio/blob/main/samples/KristofferStrube.Blazor.WebAudio.WasmExample/Pages/RecordMediaStream.razor

I am not sure how i could save the recorded byte's to a file or send them to an Api. 
I am not very familiar with handling audio.
Could you explain how this would be done or add a sample  ?

**Comment by KristofferStrube** [comment]
Hey @b4naki thanks for your interest in the library. 😁 Sorry for the slow response.

The Blazor.WebAudio library has a couple of associated libraries. One of these is the [Blazor.MediaStreamRecording](https://github.com/KristofferStrube/Blazor.MediaStreamRecording) library. This library is what is used in the above demo to record the audio.

In that repository, I have demos that show that we can download these by combining them into a single blob and then getting the blob-URL to that blob: https://kristofferstrube.github.io/Blazor.MediaStreamRecording/

Once you have that combined blob you could also read it in many other ways for example as a byte array by using the appropriate method from the [Blazor.FileAPI](https://github.com/KristofferStrube/Blazor.FileAPI) library which is the [ArrayBufferAsync method](https://github.com/KristofferStrube/Blazor.FileAPI/blob/main/src/KristofferStrube.Blazor.FileAPI/Blob.cs#L108).
