### ISSUE TITLE
Audio Routing

### ISSUE THREAD

**Issue by colombo9** [KristofferStrube/Blazor.WebAudio#7]
Thanks for an awesome library.
I have a multichannel audio interface (Presonus). How would I specify output channels in the destination node, other than the default ?

Also, having played with the Playground demo (really cool stuff) and the script below, the audio is jerky and distorted. I expected a delay, but this is too choppy.

Any help would be greatly appreciated.
Thanks,
Russ...

rect data-elementtype="media-stream-audio-source" id="2966df38" stroke="#28B6F6" stroke-width="2" height="100" width="250" x="104" y="168"></rect 
rect data-elementtype="audio-destination" id="cecb25e0" stroke="#EC407A" stroke-width="2" height="100" width="250" x="827" y="168"></rect
rect data-elementtype="gain" id="d47e6838" stroke="#EE534F" stroke-width="2" height="100" width="250" x="469" y="168" data-gain="3.9"></rect
line data-elementtype="connector" x1="364" y1="188" stroke="black" stroke-width="5" data-from-node="2966df38" x2="459" y2="188" data-to-node="d47e6838"></line
line data-elementtype="connector" x1="729" y1="188" stroke="black" stroke-width="5" data-from-node="d47e6838" x2="817" y2="188" data-to-node="cecb25e0"></line

**Comment by KristofferStrube** [comment]
Hey @colombo9 I'm happy that you are interested in the library. :)

I've made a link [here](https://kristofferstrube.github.io/Blazor.WebAudio/Playground?code=H4sIAAAAAAACA5XS0W6DIBQG4Ps9BaHXbKKCNNEm22Lfg8JpJVVYlGbt2w%2BidnbZknnlycmR%2F%2BNo2YPySEsvCbTQgfX%2B9gEV7kAbSQbfg%2ByIvGjjyOAuvQKMjK5wuuVcHzOBURhx5%2FDCJhVvfM%2FnBvk02jdhEKMGzKnxFaZJgtHcZqG%2Bxl6O0S08ucC78iViduip%2FAM1OjQM3ljpjbMjRoE6pAySBaZ%2Bz5PidSVGpMUKzEmaKV%2FnBXDxsIy6Zlm%2BX5mfMzbmFxkeA2NGhZPnB09rLPziUc7aMOH6cBatcMbjZkNBxQJ2aKU6%2F2SxKe3Yu45Yp2H5fa9pgOURFgq6nWXeTZP3ywdhlP1fWFA2CeOpa4XfS49CQYtJGG%2F7KLz%2FHrPwC%2FGoogX0AgAA) for you above sample and adjusted the gain to something within the normal range. The above sample you had made had a gain above 1 which would mean that your audio would probably hit the peak of the speaker if the volume of the speaker was set to 100%. When audio playback hits the peak of the speaker it will generally sound really bad, so normally we should not set the gain above 1.0.


What browser and operating system are you using?

**Comment by colombo9** [comment]
Hello Kritoffer,

Thanks for the speedy reply. I tried you updated URL and it works better when the source is voice, but not music. I’m attaching a sample recording of the output.

I’m using Win11 and Chrome.

Also, how do I Configure the Audio Destination to use channels other than the default ?

Thanks for your help,
Russ…

**Comment by KristofferStrube** [comment]
Hey @colombo9 you can't attach files to a response on an issue by attaching the files to an email. So I didn't get that recording.

My guess would be that some media stream that contains music could be caught by the default noise suppression or echo cancellation that is enabled in my demo which could alter the quality of the output sound. I currently don't expose a way to toggle this in the playground, but if you use the library yourself you can change this by changing these settings in the `MediaTrackConstraints` that are used for constructing the MediaStream.

With regards to your question about changing the output channel then you can alter which channel sound is output to either by using the `PannerNode` or the `ChannelSplitterNode` that are available in the library. Neither of these nodes is exposed as a part of the limited playground sample.

**Comment by colombo9** [comment]
Here's the audio sample that didn't transfer.
[ILoveYouMoreToday.zip](https://github.com/user-attachments/files/17214294/ILoveYouMoreToday.zip)
Thanks,
Russ...

**Comment by KristofferStrube** [comment]
Hey again @colombo9 I would guess that this is due to the echo cancellation or noise suppression as mentioned previously. 

I have updated the demo to disable those two features. Could you try again and see if it sounds better?

**Comment by colombo9** [comment]
Perfect. Thanks for all your help.

**Comment by KristofferStrube** [comment]
And now you can toggle this on and off in the demo directly:
![image](https://github.com/user-attachments/assets/8ad7447d-b524-455d-9935-98789f0f21f5)
